#ifndef NIGHT_CAN_IDS_H
#define NIGHT_CAN_IDS_H

// Auto-generated CAN ID header file
// Generated from: can_packets.json
// DO NOT EDIT MANUALLY

#include <stdint.h> // For fixed-width integer types

// Packet: Write Memory Data -- Firmware Update
// From: Pi
// To:   \*
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_ID 4
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_DLC 8
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FREQ 0
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_QUANTITY 0

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_0_BYTE 0
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_0_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_0_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_0_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_1_BYTE 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_1_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_1_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_1_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_2_BYTE 2
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_2_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_2_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_2_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_3_BYTE 3
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_3_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_3_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_3_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_4_BYTE 4
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_4_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_4_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_4_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_5_BYTE 5
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_5_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_5_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_5_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_6_BYTE 6
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_6_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_6_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_6_PREC 1.0f

#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_7_BYTE 7
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_7_LENGTH 1
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_7_TYPE uint8_t
#define WRITE_MEMORY_DATA_FIRMWARE_UPDATE_FIELD_7_PREC 1.0f

// End Packet: Write Memory Data -- Firmware Update

// Packet: Packet_0x010
#define PACKET_0X010_ID 16
#define PACKET_0X010_DLC 0
#define PACKET_0X010_FREQ 0
#define PACKET_0X010_QUANTITY 0

// End Packet: Packet_0x010

// Packet: Packet_0x012
#define PACKET_0X012_ID 18
#define PACKET_0X012_DLC 0
#define PACKET_0X012_FREQ 0
#define PACKET_0X012_QUANTITY 0

// End Packet: Packet_0x012

// Packet: Packet_0x013
#define PACKET_0X013_ID 19
#define PACKET_0X013_DLC 0
#define PACKET_0X013_FREQ 0
#define PACKET_0X013_QUANTITY 0

// End Packet: Packet_0x013

// Packet: Packet_0x014
// From: Pi
// To:   Undertray
#define PACKET_0X014_ID 20
#define PACKET_0X014_DLC 0
#define PACKET_0X014_FREQ 0
#define PACKET_0X014_QUANTITY 0

// End Packet: Packet_0x014

// Packet: Bus Enable/Disable
// From: Pi
// To:   HVC
#define BUS_ENABLE_DISABLE_ID 32
#define BUS_ENABLE_DISABLE_DLC 1
#define BUS_ENABLE_DISABLE_FREQ 0
#define BUS_ENABLE_DISABLE_QUANTITY 3

#define BUS_ENABLE_DISABLE_FIELD_0_BYTE 0
#define BUS_ENABLE_DISABLE_FIELD_0_LENGTH 1
#define BUS_ENABLE_DISABLE_FIELD_0_TYPE uint8_t
#define BUS_ENABLE_DISABLE_FIELD_0_PREC 1.0f

// End Packet: Bus Enable/Disable

// Packet: Bus Enable/Disable
// From: Pi
// To:   VCU
#define BUS_ENABLE_DISABLE_ID 33
#define BUS_ENABLE_DISABLE_DLC 1
#define BUS_ENABLE_DISABLE_FREQ 0
#define BUS_ENABLE_DISABLE_QUANTITY 3

#define BUS_ENABLE_DISABLE_FIELD_0_BYTE 0
#define BUS_ENABLE_DISABLE_FIELD_0_LENGTH 1
#define BUS_ENABLE_DISABLE_FIELD_0_TYPE uint8_t
#define BUS_ENABLE_DISABLE_FIELD_0_PREC 1.0f

// End Packet: Bus Enable/Disable

// Packet: Bus Enable/Disable
// From: Pi
// To:   Upright
#define BUS_ENABLE_DISABLE_ID 34
#define BUS_ENABLE_DISABLE_DLC 1
#define BUS_ENABLE_DISABLE_FREQ 0
#define BUS_ENABLE_DISABLE_QUANTITY 3

#define BUS_ENABLE_DISABLE_FIELD_0_BYTE 0
#define BUS_ENABLE_DISABLE_FIELD_0_LENGTH 1
#define BUS_ENABLE_DISABLE_FIELD_0_TYPE uint8_t
#define BUS_ENABLE_DISABLE_FIELD_0_PREC 1.0f

// End Packet: Bus Enable/Disable

// Packet: (Meta Data for Write Memory -- Firmware Update, 256B max)
// From: Pi
// To:   \*
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_ID 49
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_DLC 5
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FREQ 0
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_QUANTITY 0

#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_0_BYTE 0
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_0_LENGTH 1
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_0_TYPE uint8_t
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_0_PREC 1.0f

#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_1_BYTE 1
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_1_LENGTH 1
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_1_TYPE uint8_t
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_1_PREC 1.0f

#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_2_BYTE 2
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_2_LENGTH 1
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_2_TYPE uint8_t
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_2_PREC 1.0f

#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_3_BYTE 3
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_3_LENGTH 1
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_3_TYPE uint8_t
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_3_PREC 1.0f

#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_4_BYTE 4
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_4_LENGTH 1
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_4_TYPE uint8_t
#define META_DATA_FOR_WRITE_MEMORY_FIRMWARE_UPDATE_256B_MAX_FIELD_4_PREC 1.0f

// End Packet: (Meta Data for Write Memory -- Firmware Update, 256B max)

// Packet: Inverter Temps
// From: Inverter
// To:   VCU
#define INVERTER_TEMPS_ID 160
#define INVERTER_TEMPS_DLC 8
#define INVERTER_TEMPS_FREQ 100
#define INVERTER_TEMPS_QUANTITY 1

#define INVERTER_TEMPS_MODULE_A_TEMP_BYTE 0
#define INVERTER_TEMPS_MODULE_A_TEMP_LENGTH 2
#define INVERTER_TEMPS_MODULE_A_TEMP_TYPE int16_t
#define INVERTER_TEMPS_MODULE_A_TEMP_PREC 0.1f

#define INVERTER_TEMPS_MODULE_B_TEMP_BYTE 2
#define INVERTER_TEMPS_MODULE_B_TEMP_LENGTH 2
#define INVERTER_TEMPS_MODULE_B_TEMP_TYPE int16_t
#define INVERTER_TEMPS_MODULE_B_TEMP_PREC 1.0f

#define INVERTER_TEMPS_MODULE_C_TEMP_BYTE 4
#define INVERTER_TEMPS_MODULE_C_TEMP_LENGTH 2
#define INVERTER_TEMPS_MODULE_C_TEMP_TYPE int16_t
#define INVERTER_TEMPS_MODULE_C_TEMP_PREC 1.0f

#define INVERTER_TEMPS_GATE_DRIVER_TEMP_BYTE 6
#define INVERTER_TEMPS_GATE_DRIVER_TEMP_LENGTH 2
#define INVERTER_TEMPS_GATE_DRIVER_TEMP_TYPE int16_t
#define INVERTER_TEMPS_GATE_DRIVER_TEMP_PREC 1.0f

// End Packet: Inverter Temps

// Packet: Inverter Temps 2
// From: Inverter
// To:   VCU
#define INVERTER_TEMPS_2_ID 162
#define INVERTER_TEMPS_2_DLC 8
#define INVERTER_TEMPS_2_FREQ 100
#define INVERTER_TEMPS_2_QUANTITY 1

#define INVERTER_TEMPS_2_RTD_4_TEMP_BYTE 0
#define INVERTER_TEMPS_2_RTD_4_TEMP_LENGTH 2
#define INVERTER_TEMPS_2_RTD_4_TEMP_TYPE int16_t
#define INVERTER_TEMPS_2_RTD_4_TEMP_PREC 1.0f

#define INVERTER_TEMPS_2_RTD_5_TEMP_BYTE 2
#define INVERTER_TEMPS_2_RTD_5_TEMP_LENGTH 2
#define INVERTER_TEMPS_2_RTD_5_TEMP_TYPE int16_t
#define INVERTER_TEMPS_2_RTD_5_TEMP_PREC 1.0f

#define INVERTER_TEMPS_2_MOTOR_TEMP_BYTE 4
#define INVERTER_TEMPS_2_MOTOR_TEMP_LENGTH 2
#define INVERTER_TEMPS_2_MOTOR_TEMP_TYPE int16_t
#define INVERTER_TEMPS_2_MOTOR_TEMP_PREC 1.0f

#define INVERTER_TEMPS_2_TORQUE_SHUDDER_BYTE 6
#define INVERTER_TEMPS_2_TORQUE_SHUDDER_LENGTH 2
#define INVERTER_TEMPS_2_TORQUE_SHUDDER_TYPE int16_t
#define INVERTER_TEMPS_2_TORQUE_SHUDDER_PREC 0.1f

// End Packet: Inverter Temps 2

// Packet: Inverter Status
// From: Inverter
// To:   VCU
#define INVERTER_STATUS_ID 165
#define INVERTER_STATUS_DLC 8
#define INVERTER_STATUS_FREQ 10
#define INVERTER_STATUS_QUANTITY 1

#define INVERTER_STATUS_MOTOR_ANGLE_BYTE 0
#define INVERTER_STATUS_MOTOR_ANGLE_LENGTH 2
#define INVERTER_STATUS_MOTOR_ANGLE_TYPE int16_t
#define INVERTER_STATUS_MOTOR_ANGLE_PREC 0.1f

#define INVERTER_STATUS_MOTOR_SPEED_BYTE 2
#define INVERTER_STATUS_MOTOR_SPEED_LENGTH 2
#define INVERTER_STATUS_MOTOR_SPEED_TYPE int16_t
#define INVERTER_STATUS_MOTOR_SPEED_PREC 1.0f

#define INVERTER_STATUS_INVERTER_FREQUENCY_BYTE 4
#define INVERTER_STATUS_INVERTER_FREQUENCY_LENGTH 2
#define INVERTER_STATUS_INVERTER_FREQUENCY_TYPE int16_t
#define INVERTER_STATUS_INVERTER_FREQUENCY_PREC 0.1f

#define INVERTER_STATUS_DELTA_RESOLVER_ANGLE_BYTE 6
#define INVERTER_STATUS_DELTA_RESOLVER_ANGLE_LENGTH 2
#define INVERTER_STATUS_DELTA_RESOLVER_ANGLE_TYPE int16_t
#define INVERTER_STATUS_DELTA_RESOLVER_ANGLE_PREC 0.1f

// End Packet: Inverter Status

// Packet: Inverter Current
// From: Inverter
// To:   VCU
#define INVERTER_CURRENT_ID 166
#define INVERTER_CURRENT_DLC 8
#define INVERTER_CURRENT_FREQ 10
#define INVERTER_CURRENT_QUANTITY 1

#define INVERTER_CURRENT_PHASE_A_CURRENT_BYTE 0
#define INVERTER_CURRENT_PHASE_A_CURRENT_LENGTH 2
#define INVERTER_CURRENT_PHASE_A_CURRENT_TYPE int16_t
#define INVERTER_CURRENT_PHASE_A_CURRENT_PREC 0.1f

#define INVERTER_CURRENT_PHASE_B_CURRENT_BYTE 2
#define INVERTER_CURRENT_PHASE_B_CURRENT_LENGTH 2
#define INVERTER_CURRENT_PHASE_B_CURRENT_TYPE int16_t
#define INVERTER_CURRENT_PHASE_B_CURRENT_PREC 1.0f

#define INVERTER_CURRENT_PHASE_C_CURRENT_BYTE 4
#define INVERTER_CURRENT_PHASE_C_CURRENT_LENGTH 2
#define INVERTER_CURRENT_PHASE_C_CURRENT_TYPE int16_t
#define INVERTER_CURRENT_PHASE_C_CURRENT_PREC 1.0f

#define INVERTER_CURRENT_DC_BUS_CURRENT_BYTE 6
#define INVERTER_CURRENT_DC_BUS_CURRENT_LENGTH 2
#define INVERTER_CURRENT_DC_BUS_CURRENT_TYPE int16_t
#define INVERTER_CURRENT_DC_BUS_CURRENT_PREC 1.0f

// End Packet: Inverter Current

// Packet: Inverter Voltage
// From: Inverter
// To:   VCU
#define INVERTER_VOLTAGE_ID 167
#define INVERTER_VOLTAGE_DLC 8
#define INVERTER_VOLTAGE_FREQ 10
#define INVERTER_VOLTAGE_QUANTITY 1

#define INVERTER_VOLTAGE_DC_BUS_VOLTAGE_BYTE 0
#define INVERTER_VOLTAGE_DC_BUS_VOLTAGE_LENGTH 2
#define INVERTER_VOLTAGE_DC_BUS_VOLTAGE_TYPE int16_t
#define INVERTER_VOLTAGE_DC_BUS_VOLTAGE_PREC 0.1f

#define INVERTER_VOLTAGE_NEUTRAL_OUTPUT_VOLTAGE_BYTE 2
#define INVERTER_VOLTAGE_NEUTRAL_OUTPUT_VOLTAGE_LENGTH 2
#define INVERTER_VOLTAGE_NEUTRAL_OUTPUT_VOLTAGE_TYPE int16_t
#define INVERTER_VOLTAGE_NEUTRAL_OUTPUT_VOLTAGE_PREC 1.0f

#define INVERTER_VOLTAGE_VAB_VQ_VOLTAGE_BYTE 4
#define INVERTER_VOLTAGE_VAB_VQ_VOLTAGE_LENGTH 2
#define INVERTER_VOLTAGE_VAB_VQ_VOLTAGE_TYPE int16_t
#define INVERTER_VOLTAGE_VAB_VQ_VOLTAGE_PREC 1.0f

#define INVERTER_VOLTAGE_VBC_VD_VOLTAGE_BYTE 6
#define INVERTER_VOLTAGE_VBC_VD_VOLTAGE_LENGTH 2
#define INVERTER_VOLTAGE_VBC_VD_VOLTAGE_TYPE int16_t
#define INVERTER_VOLTAGE_VBC_VD_VOLTAGE_PREC 1.0f

// End Packet: Inverter Voltage

// Packet: Inverter Details
// From: Inverter
// To:   VCU
#define INVERTER_DETAILS_ID 170
#define INVERTER_DETAILS_DLC 8
#define INVERTER_DETAILS_FREQ 10
#define INVERTER_DETAILS_QUANTITY 1

#define INVERTER_DETAILS_VSM_BYTE 0
#define INVERTER_DETAILS_VSM_LENGTH 1
#define INVERTER_DETAILS_VSM_TYPE uint8_t
#define INVERTER_DETAILS_VSM_PREC 1.0f

#define INVERTER_DETAILS_PWM_FREQ_BYTE 1
#define INVERTER_DETAILS_PWM_FREQ_LENGTH 1
#define INVERTER_DETAILS_PWM_FREQ_TYPE uint8_t
#define INVERTER_DETAILS_PWM_FREQ_PREC 1.0f

#define INVERTER_DETAILS_INVERTER_BYTE 2
#define INVERTER_DETAILS_INVERTER_LENGTH 1
#define INVERTER_DETAILS_INVERTER_TYPE uint8_t
#define INVERTER_DETAILS_INVERTER_PREC 1.0f

#define INVERTER_DETAILS_RELAY_BYTE 3
#define INVERTER_DETAILS_RELAY_LENGTH 1
#define INVERTER_DETAILS_RELAY_TYPE uint8_t
#define INVERTER_DETAILS_RELAY_PREC 1.0f

#define INVERTER_DETAILS_MISC_1_BYTE 4
#define INVERTER_DETAILS_MISC_1_LENGTH 1
#define INVERTER_DETAILS_MISC_1_TYPE uint8_t
#define INVERTER_DETAILS_MISC_1_PREC 1.0f

#define INVERTER_DETAILS_MISC_2_BYTE 5
#define INVERTER_DETAILS_MISC_2_LENGTH 1
#define INVERTER_DETAILS_MISC_2_TYPE uint8_t
#define INVERTER_DETAILS_MISC_2_PREC 1.0f

#define INVERTER_DETAILS_MISC_3_BYTE 6
#define INVERTER_DETAILS_MISC_3_LENGTH 1
#define INVERTER_DETAILS_MISC_3_TYPE uint8_t
#define INVERTER_DETAILS_MISC_3_PREC 1.0f

#define INVERTER_DETAILS_MISC_4_BYTE 7
#define INVERTER_DETAILS_MISC_4_LENGTH 1
#define INVERTER_DETAILS_MISC_4_TYPE uint8_t
#define INVERTER_DETAILS_MISC_4_PREC 1.0f

// End Packet: Inverter Details

// Packet: Inverter Faults
// From: Inverter
// To:   VCU
#define INVERTER_FAULTS_ID 171
#define INVERTER_FAULTS_DLC 8
#define INVERTER_FAULTS_FREQ 10
#define INVERTER_FAULTS_QUANTITY 1

#define INVERTER_FAULTS_POST_FAULTS_BYTE 0
#define INVERTER_FAULTS_POST_FAULTS_LENGTH 4
#define INVERTER_FAULTS_POST_FAULTS_TYPE uint32_t
#define INVERTER_FAULTS_POST_FAULTS_PREC 1.0f

#define INVERTER_FAULTS_RUN_FAULTS_BYTE 4
#define INVERTER_FAULTS_RUN_FAULTS_LENGTH 4
#define INVERTER_FAULTS_RUN_FAULTS_TYPE uint32_t
#define INVERTER_FAULTS_RUN_FAULTS_PREC 1.0f

// End Packet: Inverter Faults

// Packet: Inverter TSO
// From: Inverter
// To:   VCU
#define INVERTER_TSO_ID 172
#define INVERTER_TSO_DLC 8
#define INVERTER_TSO_FREQ 10
#define INVERTER_TSO_QUANTITY 1

#define INVERTER_TSO_COMMANDED_TORQUE_BYTE 0
#define INVERTER_TSO_COMMANDED_TORQUE_LENGTH 2
#define INVERTER_TSO_COMMANDED_TORQUE_TYPE int16_t
#define INVERTER_TSO_COMMANDED_TORQUE_PREC 0.1f

#define INVERTER_TSO_TORQUE_FEEDBACK_BYTE 2
#define INVERTER_TSO_TORQUE_FEEDBACK_LENGTH 2
#define INVERTER_TSO_TORQUE_FEEDBACK_TYPE int16_t
#define INVERTER_TSO_TORQUE_FEEDBACK_PREC 1.0f

#define INVERTER_TSO_TIME_SINCE_TURNED_ON_BYTE 4
#define INVERTER_TSO_TIME_SINCE_TURNED_ON_LENGTH 4
#define INVERTER_TSO_TIME_SINCE_TURNED_ON_TYPE uint32_t
#define INVERTER_TSO_TIME_SINCE_TURNED_ON_PREC 1.0f

// End Packet: Inverter TSO

// Packet: Inverter Speed
// From: Inverter
// To:   VCU
#define INVERTER_SPEED_ID 176
#define INVERTER_SPEED_DLC 8
#define INVERTER_SPEED_FREQ 3
#define INVERTER_SPEED_QUANTITY 1

#define INVERTER_SPEED_COMMANDED_TORQUE_BYTE 0
#define INVERTER_SPEED_COMMANDED_TORQUE_LENGTH 2
#define INVERTER_SPEED_COMMANDED_TORQUE_TYPE int16_t
#define INVERTER_SPEED_COMMANDED_TORQUE_PREC 1.0f

#define INVERTER_SPEED_TORQUE_FEEDBACK_BYTE 2
#define INVERTER_SPEED_TORQUE_FEEDBACK_LENGTH 2
#define INVERTER_SPEED_TORQUE_FEEDBACK_TYPE int16_t
#define INVERTER_SPEED_TORQUE_FEEDBACK_PREC 1.0f

#define INVERTER_SPEED_MOTOR_SPEED_BYTE 4
#define INVERTER_SPEED_MOTOR_SPEED_LENGTH 2
#define INVERTER_SPEED_MOTOR_SPEED_TYPE int16_t
#define INVERTER_SPEED_MOTOR_SPEED_PREC 1.0f

#define INVERTER_SPEED_BUS_VOLTAGE_BYTE 6
#define INVERTER_SPEED_BUS_VOLTAGE_LENGTH 2
#define INVERTER_SPEED_BUS_VOLTAGE_TYPE uint16_t
#define INVERTER_SPEED_BUS_VOLTAGE_PREC 1.0f

// End Packet: Inverter Speed

// Packet: Inverter Torque Command
// From: VCU
// To:   Inverter
#define INVERTER_TORQUE_COMMAND_ID 192
#define INVERTER_TORQUE_COMMAND_DLC 8
#define INVERTER_TORQUE_COMMAND_FREQ 3
#define INVERTER_TORQUE_COMMAND_QUANTITY 1

#define INVERTER_TORQUE_COMMAND_TORQUE_REQUEST_BYTE 0
#define INVERTER_TORQUE_COMMAND_TORQUE_REQUEST_LENGTH 2
#define INVERTER_TORQUE_COMMAND_TORQUE_REQUEST_TYPE int16_t
#define INVERTER_TORQUE_COMMAND_TORQUE_REQUEST_PREC 0.1f

#define INVERTER_TORQUE_COMMAND_RPM_REQUEST_BYTE 2
#define INVERTER_TORQUE_COMMAND_RPM_REQUEST_LENGTH 2
#define INVERTER_TORQUE_COMMAND_RPM_REQUEST_TYPE int16_t
#define INVERTER_TORQUE_COMMAND_RPM_REQUEST_PREC 1.0f

#define INVERTER_TORQUE_COMMAND_DIRECTION_BYTE 4
#define INVERTER_TORQUE_COMMAND_DIRECTION_LENGTH 1
#define INVERTER_TORQUE_COMMAND_DIRECTION_TYPE uint8_t
#define INVERTER_TORQUE_COMMAND_DIRECTION_PREC 1.0f

#define INVERTER_TORQUE_COMMAND_ENABLE_BYTE 5
#define INVERTER_TORQUE_COMMAND_ENABLE_LENGTH 1
#define INVERTER_TORQUE_COMMAND_ENABLE_TYPE uint8_t
#define INVERTER_TORQUE_COMMAND_ENABLE_PREC 1.0f

#define INVERTER_TORQUE_COMMAND_TORQUE_LIMIT_BYTE 6
#define INVERTER_TORQUE_COMMAND_TORQUE_LIMIT_LENGTH 2
#define INVERTER_TORQUE_COMMAND_TORQUE_LIMIT_TYPE int16_t
#define INVERTER_TORQUE_COMMAND_TORQUE_LIMIT_PREC 0.1f

// End Packet: Inverter Torque Command

// Packet: Inverter Parameter Request
// From: VCU
// To:   Inverter
#define INVERTER_PARAMETER_REQUEST_ID 193
#define INVERTER_PARAMETER_REQUEST_DLC 8
#define INVERTER_PARAMETER_REQUEST_FREQ 0
#define INVERTER_PARAMETER_REQUEST_QUANTITY 1

#define INVERTER_PARAMETER_REQUEST_PARAMETER_ADDRESS_BYTE 0
#define INVERTER_PARAMETER_REQUEST_PARAMETER_ADDRESS_LENGTH 2
#define INVERTER_PARAMETER_REQUEST_PARAMETER_ADDRESS_TYPE uint16_t
#define INVERTER_PARAMETER_REQUEST_PARAMETER_ADDRESS_PREC 1.0f

#define INVERTER_PARAMETER_REQUEST_R_W_BYTE 2
#define INVERTER_PARAMETER_REQUEST_R_W_LENGTH 1
// Warning: Unknown conversion type '0/1' - _TYPE define omitted.
#define INVERTER_PARAMETER_REQUEST_R_W_PREC 1.0f

// End Packet: Inverter Parameter Request

// Packet: Inverter Parameter Response
// From: Inverter
// To:   VCU
#define INVERTER_PARAMETER_RESPONSE_ID 194
#define INVERTER_PARAMETER_RESPONSE_DLC 8
#define INVERTER_PARAMETER_RESPONSE_FREQ 0
#define INVERTER_PARAMETER_RESPONSE_QUANTITY 1

#define INVERTER_PARAMETER_RESPONSE_PARAMETER_ADDRESS_BYTE 0
#define INVERTER_PARAMETER_RESPONSE_PARAMETER_ADDRESS_LENGTH 2
#define INVERTER_PARAMETER_RESPONSE_PARAMETER_ADDRESS_TYPE uint16_t
#define INVERTER_PARAMETER_RESPONSE_PARAMETER_ADDRESS_PREC 1.0f

#define INVERTER_PARAMETER_RESPONSE_SUCCESS_BYTE 2
#define INVERTER_PARAMETER_RESPONSE_SUCCESS_LENGTH 1
#define INVERTER_PARAMETER_RESPONSE_SUCCESS_TYPE uint8_t
#define INVERTER_PARAMETER_RESPONSE_SUCCESS_PREC 1.0f

// End Packet: Inverter Parameter Response

// Packet: Wheel Speed, Ride height
// From: Upright
// To:   VCU
#define WHEEL_SPEED_RIDE_HEIGHT_ID 209
#define WHEEL_SPEED_RIDE_HEIGHT_DLC 4
#define WHEEL_SPEED_RIDE_HEIGHT_FREQ 10
#define WHEEL_SPEED_RIDE_HEIGHT_QUANTITY 1

#define WHEEL_SPEED_RIDE_HEIGHT_WHEEL_SPEED_BYTE 0
#define WHEEL_SPEED_RIDE_HEIGHT_WHEEL_SPEED_LENGTH 2
#define WHEEL_SPEED_RIDE_HEIGHT_WHEEL_SPEED_TYPE int16_t
#define WHEEL_SPEED_RIDE_HEIGHT_WHEEL_SPEED_PREC 0.0078125f

#define WHEEL_SPEED_RIDE_HEIGHT_RIDE_HEIGHT_BYTE 2
#define WHEEL_SPEED_RIDE_HEIGHT_RIDE_HEIGHT_LENGTH 2
#define WHEEL_SPEED_RIDE_HEIGHT_RIDE_HEIGHT_TYPE uint16_t
#define WHEEL_SPEED_RIDE_HEIGHT_RIDE_HEIGHT_PREC 0.0625f

// End Packet: Wheel Speed, Ride height

// Packet: APPS Voltages
// From: Rack
// To:   VCU
#define APPS_VOLTAGES_ID 2560
#define APPS_VOLTAGES_DLC 8
#define APPS_VOLTAGES_FREQ 3
#define APPS_VOLTAGES_QUANTITY 1

#define APPS_VOLTAGES_APPS1_VOLTAGE_BYTE 0
#define APPS_VOLTAGES_APPS1_VOLTAGE_LENGTH 2
#define APPS_VOLTAGES_APPS1_VOLTAGE_TYPE uint16_t
#define APPS_VOLTAGES_APPS1_VOLTAGE_PREC 0.0001f

#define APPS_VOLTAGES_APPS2_VOLTAGE_BYTE 2
#define APPS_VOLTAGES_APPS2_VOLTAGE_LENGTH 2
#define APPS_VOLTAGES_APPS2_VOLTAGE_TYPE uint16_t
#define APPS_VOLTAGES_APPS2_VOLTAGE_PREC 0.0001f

#define APPS_VOLTAGES_APPS1_TRAVEL_BYTE 4
#define APPS_VOLTAGES_APPS1_TRAVEL_LENGTH 2
#define APPS_VOLTAGES_APPS1_TRAVEL_TYPE uint16_t
#define APPS_VOLTAGES_APPS1_TRAVEL_PREC 0.0001f

#define APPS_VOLTAGES_APPS2_TRAVEL_BYTE 6
#define APPS_VOLTAGES_APPS2_TRAVEL_LENGTH 2
#define APPS_VOLTAGES_APPS2_TRAVEL_TYPE uint16_t
#define APPS_VOLTAGES_APPS2_TRAVEL_PREC 0.0001f

// End Packet: APPS Voltages

// Packet: Accelerator Pedal
// From: Rack
// To:   VCU
#define ACCELERATOR_PEDAL_ID 2561
#define ACCELERATOR_PEDAL_DLC 3
#define ACCELERATOR_PEDAL_FREQ 3
#define ACCELERATOR_PEDAL_QUANTITY 1

#define ACCELERATOR_PEDAL_ACCELERATOR_PEDAL_TRAVEL_BYTE 0
#define ACCELERATOR_PEDAL_ACCELERATOR_PEDAL_TRAVEL_LENGTH 2
#define ACCELERATOR_PEDAL_ACCELERATOR_PEDAL_TRAVEL_TYPE uint16_t
#define ACCELERATOR_PEDAL_ACCELERATOR_PEDAL_TRAVEL_PREC 0.0001f

#define ACCELERATOR_PEDAL_APPS_FAULTS_BYTE 2
#define ACCELERATOR_PEDAL_APPS_FAULTS_LENGTH 1
// --- Bitfield Indices for: APPS Faults ---
#define ACCELERATOR_PEDAL_APPS_FAULTS_APPS1_DISCONNECT_IDX 0
#define ACCELERATOR_PEDAL_APPS_FAULTS_APPS2_DISCONNECT_IDX 1
#define ACCELERATOR_PEDAL_APPS_FAULTS_APPS1_OUT_RANGE_IDX 2
#define ACCELERATOR_PEDAL_APPS_FAULTS_APPS2_OUT_RANGE_IDX 3
#define ACCELERATOR_PEDAL_APPS_FAULTS_APPS_MISMATCH_IDX 4
#define ACCELERATOR_PEDAL_APPS_FAULTS_APPS_IMPLAUSE_IDX 5

// End Packet: Accelerator Pedal

// Packet: BPPS Voltages
// From: Rack
// To:   VCU
#define BPPS_VOLTAGES_ID 2562
#define BPPS_VOLTAGES_DLC 8
#define BPPS_VOLTAGES_FREQ 3
#define BPPS_VOLTAGES_QUANTITY 1

#define BPPS_VOLTAGES_BPPS1_VOLTAGE_BYTE 0
#define BPPS_VOLTAGES_BPPS1_VOLTAGE_LENGTH 2
#define BPPS_VOLTAGES_BPPS1_VOLTAGE_TYPE uint16_t
#define BPPS_VOLTAGES_BPPS1_VOLTAGE_PREC 0.0001f

#define BPPS_VOLTAGES_BPPS2_VOLTAGE_BYTE 2
#define BPPS_VOLTAGES_BPPS2_VOLTAGE_LENGTH 2
#define BPPS_VOLTAGES_BPPS2_VOLTAGE_TYPE uint16_t
#define BPPS_VOLTAGES_BPPS2_VOLTAGE_PREC 0.0001f

#define BPPS_VOLTAGES_BPPS1_TRAVEL_BYTE 4
#define BPPS_VOLTAGES_BPPS1_TRAVEL_LENGTH 2
#define BPPS_VOLTAGES_BPPS1_TRAVEL_TYPE uint16_t
#define BPPS_VOLTAGES_BPPS1_TRAVEL_PREC 0.0001f

#define BPPS_VOLTAGES_BPPS2_TRAVEL_BYTE 6
#define BPPS_VOLTAGES_BPPS2_TRAVEL_LENGTH 2
#define BPPS_VOLTAGES_BPPS2_TRAVEL_TYPE uint16_t
#define BPPS_VOLTAGES_BPPS2_TRAVEL_PREC 0.0001f

// End Packet: BPPS Voltages

// Packet: Brake Pedal
// From: Rack
// To:   VCU
#define BRAKE_PEDAL_ID 2563
#define BRAKE_PEDAL_DLC 3
#define BRAKE_PEDAL_FREQ 3
#define BRAKE_PEDAL_QUANTITY 1

#define BRAKE_PEDAL_BRAKE_PEDAL_TRAVEL_BYTE 0
#define BRAKE_PEDAL_BRAKE_PEDAL_TRAVEL_LENGTH 2
#define BRAKE_PEDAL_BRAKE_PEDAL_TRAVEL_TYPE uint16_t
#define BRAKE_PEDAL_BRAKE_PEDAL_TRAVEL_PREC 0.0001f

#define BRAKE_PEDAL_BPPS_FAULTS_BYTE 2
#define BRAKE_PEDAL_BPPS_FAULTS_LENGTH 1
// --- Bitfield Indices for: BPPS Faults ---
#define BRAKE_PEDAL_BPPS_FAULTS_BPPS1_DISCONNECT_IDX 0
#define BRAKE_PEDAL_BPPS_FAULTS_BPPS2_DISCONNECT_IDX 1
#define BRAKE_PEDAL_BPPS_FAULTS_BPPS1_OUT_RANGE_IDX 2
#define BRAKE_PEDAL_BPPS_FAULTS_BPPS2_OUT_RANGE_IDX 3
#define BRAKE_PEDAL_BPPS_FAULTS_BPPS_MISMATCH_IDX 4

// End Packet: Brake Pedal

// Packet: BSE Voltages
// From: VCU
// To:   Pi
#define BSE_VOLTAGES_ID 256
#define BSE_VOLTAGES_DLC 6
#define BSE_VOLTAGES_FREQ 3
#define BSE_VOLTAGES_QUANTITY 1

#define BSE_VOLTAGES_BSE_FRONT_VOLTAGE_BYTE 0
#define BSE_VOLTAGES_BSE_FRONT_VOLTAGE_LENGTH 2
#define BSE_VOLTAGES_BSE_FRONT_VOLTAGE_TYPE uint16_t
#define BSE_VOLTAGES_BSE_FRONT_VOLTAGE_PREC 0.0001f

#define BSE_VOLTAGES_BSE_REAR_VOLTAGE_BYTE 2
#define BSE_VOLTAGES_BSE_REAR_VOLTAGE_LENGTH 2
#define BSE_VOLTAGES_BSE_REAR_VOLTAGE_TYPE uint16_t
#define BSE_VOLTAGES_BSE_REAR_VOLTAGE_PREC 0.0001f

#define BSE_VOLTAGES_BSE_LINE_LOCK_VOLTAGE_BYTE 4
#define BSE_VOLTAGES_BSE_LINE_LOCK_VOLTAGE_LENGTH 2
#define BSE_VOLTAGES_BSE_LINE_LOCK_VOLTAGE_TYPE uint16_t
#define BSE_VOLTAGES_BSE_LINE_LOCK_VOLTAGE_PREC 0.0001f

// End Packet: BSE Voltages

// Packet: Brakes
// From: Rack
// To:   Pi
#define BRAKES_ID 2564
#define BRAKES_DLC 8
#define BRAKES_FREQ 3
#define BRAKES_QUANTITY 1

#define BRAKES_BRAKE_PRESSURE_FRONT_BYTE 0
#define BRAKES_BRAKE_PRESSURE_FRONT_LENGTH 2
#define BRAKES_BRAKE_PRESSURE_FRONT_TYPE uint16_t
#define BRAKES_BRAKE_PRESSURE_FRONT_PREC 0.05f

#define BRAKES_BRAKE_PRESSURE_REAR_PRE_LOCK_BYTE 2
#define BRAKES_BRAKE_PRESSURE_REAR_PRE_LOCK_LENGTH 2
#define BRAKES_BRAKE_PRESSURE_REAR_PRE_LOCK_TYPE uint16_t
#define BRAKES_BRAKE_PRESSURE_REAR_PRE_LOCK_PREC 0.05f

#define BRAKES_BRAKE_PRESSURE_REAR_POST_LOCK_BYTE 4
#define BRAKES_BRAKE_PRESSURE_REAR_POST_LOCK_LENGTH 2
#define BRAKES_BRAKE_PRESSURE_REAR_POST_LOCK_TYPE uint16_t
#define BRAKES_BRAKE_PRESSURE_REAR_POST_LOCK_PREC 0.05f

#define BRAKES_BRAKE_BIAS_BYTE 6
#define BRAKES_BRAKE_BIAS_LENGTH 1
#define BRAKES_BRAKE_BIAS_TYPE uint8_t
#define BRAKES_BRAKE_BIAS_PREC 0.01f

#define BRAKES_BSE_FAULTS_BYTE 7
#define BRAKES_BSE_FAULTS_LENGTH 1
// --- Bitfield Indices for: BSE Faults ---
#define BRAKES_BSE_FAULTS_BSE1_DISCONNECT_IDX 0
#define BRAKES_BSE_FAULTS_BSE2_DISCONNECT_IDX 1
#define BRAKES_BSE_FAULTS_BSE1_OUT_RANGE_IDX 2
#define BRAKES_BSE_FAULTS_BSE2_OUT_RANGE_IDX 3

// End Packet: Brakes

// Packet: Rack Steering
// From: Rack
// To:   Pi
#define RACK_STEERING_ID 2565
#define RACK_STEERING_DLC 2
#define RACK_STEERING_FREQ 3
#define RACK_STEERING_QUANTITY 1

#define RACK_STEERING_STEERING_COLUMN_ANGLE_BYTE 0
#define RACK_STEERING_STEERING_COLUMN_ANGLE_LENGTH 2
#define RACK_STEERING_STEERING_COLUMN_ANGLE_TYPE int16_t
#define RACK_STEERING_STEERING_COLUMN_ANGLE_PREC 0.004f

// End Packet: Rack Steering

// Packet: FL Steering
// From: Upright
// To:   Pi
#define FL_STEERING_ID 1024
#define FL_STEERING_DLC 2
#define FL_STEERING_FREQ 3
#define FL_STEERING_QUANTITY 1

#define FL_STEERING_FL_EST_STEERING_ANGLE_BYTE 0
#define FL_STEERING_FL_EST_STEERING_ANGLE_LENGTH 2
#define FL_STEERING_FL_EST_STEERING_ANGLE_TYPE int16_t
#define FL_STEERING_FL_EST_STEERING_ANGLE_PREC 0.001f

// End Packet: FL Steering

// Packet: FR Steering
// From: Upright
// To:   Pi
#define FR_STEERING_ID 1025
#define FR_STEERING_DLC 2
#define FR_STEERING_FREQ 3
#define FR_STEERING_QUANTITY 1

#define FR_STEERING_FR_EST_STEERING_ANGLE_BYTE 0
#define FR_STEERING_FR_EST_STEERING_ANGLE_LENGTH 2
#define FR_STEERING_FR_EST_STEERING_ANGLE_TYPE int16_t
#define FR_STEERING_FR_EST_STEERING_ANGLE_PREC 0.001f

// End Packet: FR Steering

// Packet: Acceleration Vector Unsprung FL
// From: Upright
// To:   Pi
#define ACCELERATION_VECTOR_UNSPRUNG_FL_ID 1026
#define ACCELERATION_VECTOR_UNSPRUNG_FL_DLC 6
#define ACCELERATION_VECTOR_UNSPRUNG_FL_FREQ 10
#define ACCELERATION_VECTOR_UNSPRUNG_FL_QUANTITY 1

#define ACCELERATION_VECTOR_UNSPRUNG_FL_X_BYTE 0
#define ACCELERATION_VECTOR_UNSPRUNG_FL_X_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_FL_X_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_FL_X_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_FL_Y_BYTE 2
#define ACCELERATION_VECTOR_UNSPRUNG_FL_Y_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_FL_Y_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_FL_Y_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_FL_Z_BYTE 4
#define ACCELERATION_VECTOR_UNSPRUNG_FL_Z_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_FL_Z_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_FL_Z_PREC 0.001f

// End Packet: Acceleration Vector Unsprung FL

// Packet: Acceleration Vector Unsprung FR
// From: Upright
// To:   Pi
#define ACCELERATION_VECTOR_UNSPRUNG_FR_ID 1027
#define ACCELERATION_VECTOR_UNSPRUNG_FR_DLC 6
#define ACCELERATION_VECTOR_UNSPRUNG_FR_FREQ 10
#define ACCELERATION_VECTOR_UNSPRUNG_FR_QUANTITY 1

#define ACCELERATION_VECTOR_UNSPRUNG_FR_X_BYTE 0
#define ACCELERATION_VECTOR_UNSPRUNG_FR_X_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_FR_X_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_FR_X_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_FR_Y_BYTE 2
#define ACCELERATION_VECTOR_UNSPRUNG_FR_Y_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_FR_Y_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_FR_Y_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_FR_Z_BYTE 4
#define ACCELERATION_VECTOR_UNSPRUNG_FR_Z_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_FR_Z_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_FR_Z_PREC 0.001f

// End Packet: Acceleration Vector Unsprung FR

// Packet: Acceleration Vector Unsprung RL
// From: Upright
// To:   Pi
#define ACCELERATION_VECTOR_UNSPRUNG_RL_ID 1028
#define ACCELERATION_VECTOR_UNSPRUNG_RL_DLC 6
#define ACCELERATION_VECTOR_UNSPRUNG_RL_FREQ 10
#define ACCELERATION_VECTOR_UNSPRUNG_RL_QUANTITY 1

#define ACCELERATION_VECTOR_UNSPRUNG_RL_X_BYTE 0
#define ACCELERATION_VECTOR_UNSPRUNG_RL_X_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_RL_X_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_RL_X_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_RL_Y_BYTE 2
#define ACCELERATION_VECTOR_UNSPRUNG_RL_Y_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_RL_Y_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_RL_Y_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_RL_Z_BYTE 4
#define ACCELERATION_VECTOR_UNSPRUNG_RL_Z_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_RL_Z_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_RL_Z_PREC 0.001f

// End Packet: Acceleration Vector Unsprung RL

// Packet: Acceleration Vector Unsprung RR
// From: Upright
// To:   Pi
#define ACCELERATION_VECTOR_UNSPRUNG_RR_ID 1029
#define ACCELERATION_VECTOR_UNSPRUNG_RR_DLC 6
#define ACCELERATION_VECTOR_UNSPRUNG_RR_FREQ 10
#define ACCELERATION_VECTOR_UNSPRUNG_RR_QUANTITY 1

#define ACCELERATION_VECTOR_UNSPRUNG_RR_X_BYTE 0
#define ACCELERATION_VECTOR_UNSPRUNG_RR_X_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_RR_X_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_RR_X_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_RR_Y_BYTE 2
#define ACCELERATION_VECTOR_UNSPRUNG_RR_Y_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_RR_Y_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_RR_Y_PREC 0.001f

#define ACCELERATION_VECTOR_UNSPRUNG_RR_Z_BYTE 4
#define ACCELERATION_VECTOR_UNSPRUNG_RR_Z_LENGTH 2
#define ACCELERATION_VECTOR_UNSPRUNG_RR_Z_TYPE int16_t
#define ACCELERATION_VECTOR_UNSPRUNG_RR_Z_PREC 0.001f

// End Packet: Acceleration Vector Unsprung RR

// Packet: Acceleration Vector Sprung + Ride Height FL
// From: Undertray
// To:   Pi
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_ID 1280
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_DLC 8
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_FREQ 10
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_QUANTITY 1

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_X_BYTE 0
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_X_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_X_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_X_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Y_BYTE 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Y_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Y_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Y_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Z_BYTE 4
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Z_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Z_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_Z_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_RIDE_HEIGHT_BYTE 6
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_RIDE_HEIGHT_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_RIDE_HEIGHT_TYPE uint16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FL_RIDE_HEIGHT_PREC 0.002f

// End Packet: Acceleration Vector Sprung + Ride Height FL

// Packet: Acceleration Vector Sprung + Ride Height FR
// From: Undertray
// To:   Pi
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_ID 1281
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_DLC 8
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_FREQ 10
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_QUANTITY 1

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_X_BYTE 0
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_X_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_X_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_X_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Y_BYTE 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Y_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Y_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Y_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Z_BYTE 4
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Z_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Z_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_Z_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_RIDE_HEIGHT_BYTE 6
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_RIDE_HEIGHT_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_RIDE_HEIGHT_TYPE uint16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_FR_RIDE_HEIGHT_PREC 0.002f

// End Packet: Acceleration Vector Sprung + Ride Height FR

// Packet: Acceleration Vector Sprung + Ride Height RL
// From: Undertray
// To:   Pi
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_ID 1282
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_DLC 8
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_FREQ 10
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_QUANTITY 1

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_X_BYTE 0
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_X_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_X_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_X_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Y_BYTE 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Y_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Y_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Y_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Z_BYTE 4
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Z_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Z_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_Z_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_RIDE_HEIGHT_BYTE 6
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_RIDE_HEIGHT_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_RIDE_HEIGHT_TYPE uint16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RL_RIDE_HEIGHT_PREC 0.002f

// End Packet: Acceleration Vector Sprung + Ride Height RL

// Packet: Acceleration Vector Sprung + Ride Height RR
// From: Undertray
// To:   Pi
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_ID 1283
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_DLC 8
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_FREQ 10
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_QUANTITY 1

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_X_BYTE 0
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_X_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_X_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_X_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Y_BYTE 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Y_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Y_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Y_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Z_BYTE 4
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Z_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Z_TYPE int16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_Z_PREC 0.001f

#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_RIDE_HEIGHT_BYTE 6
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_RIDE_HEIGHT_LENGTH 2
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_RIDE_HEIGHT_TYPE uint16_t
#define ACCELERATION_VECTOR_SPRUNG_RIDE_HEIGHT_RR_RIDE_HEIGHT_PREC 0.002f

// End Packet: Acceleration Vector Sprung + Ride Height RR

// Packet: Angular Rate Vector FL Sprung
// From: Undertray
// To:   Pi
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_ID 1284
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_DLC 6
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_FREQ 10
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_QUANTITY 1

#define ANGULAR_RATE_VECTOR_FL_SPRUNG_X_BYTE 0
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_X_LENGTH 2
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_X_TYPE int16_t
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_X_PREC 0.03f

#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Y_BYTE 2
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Y_LENGTH 2
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Y_TYPE int16_t
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Y_PREC 0.03f

#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Z_BYTE 4
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Z_LENGTH 2
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Z_TYPE int16_t
#define ANGULAR_RATE_VECTOR_FL_SPRUNG_Z_PREC 0.03f

// End Packet: Angular Rate Vector FL Sprung

// Packet: Angular Rate Vector FR Sprung
// From: Undertray
// To:   Pi
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_ID 1285
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_DLC 6
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_FREQ 10
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_QUANTITY 1

#define ANGULAR_RATE_VECTOR_FR_SPRUNG_X_BYTE 0
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_X_LENGTH 2
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_X_TYPE int16_t
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_X_PREC 0.03f

#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Y_BYTE 2
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Y_LENGTH 2
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Y_TYPE int16_t
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Y_PREC 0.03f

#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Z_BYTE 4
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Z_LENGTH 2
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Z_TYPE int16_t
#define ANGULAR_RATE_VECTOR_FR_SPRUNG_Z_PREC 0.03f

// End Packet: Angular Rate Vector FR Sprung

// Packet: Angular Rate Vector BL Sprung
// From: Undertray
// To:   Pi
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_ID 1286
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_DLC 6
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_FREQ 10
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_QUANTITY 1

#define ANGULAR_RATE_VECTOR_BL_SPRUNG_X_BYTE 0
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_X_LENGTH 2
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_X_TYPE int16_t
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_X_PREC 0.03f

#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Y_BYTE 2
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Y_LENGTH 2
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Y_TYPE int16_t
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Y_PREC 0.03f

#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Z_BYTE 4
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Z_LENGTH 2
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Z_TYPE int16_t
#define ANGULAR_RATE_VECTOR_BL_SPRUNG_Z_PREC 0.03f

// End Packet: Angular Rate Vector BL Sprung

// Packet: Angular Rate Vector BR Sprung
// From: Undertray
// To:   Pi
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_ID 1287
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_DLC 6
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_FREQ 10
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_QUANTITY 1

#define ANGULAR_RATE_VECTOR_BR_SPRUNG_X_BYTE 0
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_X_LENGTH 2
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_X_TYPE int16_t
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_X_PREC 0.03f

#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Y_BYTE 2
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Y_LENGTH 2
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Y_TYPE int16_t
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Y_PREC 0.03f

#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Z_BYTE 4
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Z_LENGTH 2
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Z_TYPE int16_t
#define ANGULAR_RATE_VECTOR_BR_SPRUNG_Z_PREC 0.03f

// End Packet: Angular Rate Vector BR Sprung

// Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. FL
// From: Upright
// To:   Pi
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_ID 1030
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_DLC 8
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_FREQ 10
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_QUANTITY 1

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPEED_BYTE 0
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPEED_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPEED_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPEED_PREC 0.01f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_STRAIN_GAUGE_VOLTAGE_BYTE 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_STRAIN_GAUGE_VOLTAGE_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_STRAIN_GAUGE_VOLTAGE_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_STRAIN_GAUGE_VOLTAGE_PREC 0.0002f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_PUSHROD_BYTE 4
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_PUSHROD_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_PUSHROD_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_PUSHROD_PREC 0.5f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPRING_DISPLACEMENT_BYTE 6
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPRING_DISPLACEMENT_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPRING_DISPLACEMENT_TYPE uint16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FL_SPRING_DISPLACEMENT_PREC 0.001f

// End Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. FL

// Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. FR
// From: Upright
// To:   Pi
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_ID 1031
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_DLC 8
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_FREQ 10
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_QUANTITY 1

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPEED_BYTE 0
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPEED_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPEED_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPEED_PREC 0.01f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_STRAIN_GAUGE_VOLTAGE_BYTE 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_STRAIN_GAUGE_VOLTAGE_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_STRAIN_GAUGE_VOLTAGE_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_STRAIN_GAUGE_VOLTAGE_PREC 0.0002f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_PUSHROD_BYTE 4
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_PUSHROD_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_PUSHROD_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_PUSHROD_PREC 0.5f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPRING_DISPLACEMENT_BYTE 6
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPRING_DISPLACEMENT_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPRING_DISPLACEMENT_TYPE uint16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_FR_SPRING_DISPLACEMENT_PREC 0.001f

// End Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. FR

// Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. RL
// From: Upright
// To:   Pi
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_ID 1032
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_DLC 8
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_FREQ 10
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_QUANTITY 1

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPEED_BYTE 0
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPEED_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPEED_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPEED_PREC 0.01f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_STRAIN_GAUGE_VOLTAGE_BYTE 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_STRAIN_GAUGE_VOLTAGE_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_STRAIN_GAUGE_VOLTAGE_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_STRAIN_GAUGE_VOLTAGE_PREC 0.0002f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_PUSHROD_BYTE 4
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_PUSHROD_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_PUSHROD_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_PUSHROD_PREC 0.5f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPRING_DISPLACEMENT_BYTE 6
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPRING_DISPLACEMENT_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPRING_DISPLACEMENT_TYPE uint16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RL_SPRING_DISPLACEMENT_PREC 0.001f

// End Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. RL

// Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. RR
// From: Upright
// To:   Pi
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_ID 1033
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_DLC 8
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_FREQ 10
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_QUANTITY 1

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPEED_BYTE 0
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPEED_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPEED_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPEED_PREC 0.01f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_STRAIN_GAUGE_VOLTAGE_BYTE 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_STRAIN_GAUGE_VOLTAGE_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_STRAIN_GAUGE_VOLTAGE_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_STRAIN_GAUGE_VOLTAGE_PREC 0.0002f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_PUSHROD_BYTE 4
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_PUSHROD_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_PUSHROD_TYPE int16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_PUSHROD_PREC 0.5f

#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPRING_DISPLACEMENT_BYTE 6
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPRING_DISPLACEMENT_LENGTH 2
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPRING_DISPLACEMENT_TYPE uint16_t
#define WHEEL_SPEED_STRAIN_GAUGE_PUSHROD_SPRING_DISP_RR_SPRING_DISPLACEMENT_PREC 0.001f

// End Packet: Wheel Speed + Strain Gauge + Pushrod + Spring Disp. RR

// Packet: GPS
// From: VCU
// To:   Pi
#define GPS_ID 257
#define GPS_DLC 8
#define GPS_FREQ 100
#define GPS_QUANTITY 1

#define GPS_REAR_LONGITUDE_BYTE 0
#define GPS_REAR_LONGITUDE_LENGTH 2
#define GPS_REAR_LONGITUDE_TYPE int16_t
#define GPS_REAR_LONGITUDE_PREC 0.001f

#define GPS_REAR_LATITUDE_BYTE 2
#define GPS_REAR_LATITUDE_LENGTH 2
#define GPS_REAR_LATITUDE_TYPE int16_t
#define GPS_REAR_LATITUDE_PREC 0.001f

#define GPS_REAR_SPEED_BYTE 4
#define GPS_REAR_SPEED_LENGTH 2
#define GPS_REAR_SPEED_TYPE uint16_t
#define GPS_REAR_SPEED_PREC 0.001f

#define GPS_REAR_HEADING_BYTE 6
#define GPS_REAR_HEADING_LENGTH 2
#define GPS_REAR_HEADING_TYPE uint16_t
#define GPS_REAR_HEADING_PREC 0.001f

// End Packet: GPS

// Packet: Motor Cooling
// From: VCU
// To:   Pi
#define MOTOR_COOLING_ID 258
#define MOTOR_COOLING_DLC 8
#define MOTOR_COOLING_FREQ 10
#define MOTOR_COOLING_QUANTITY 1

#define MOTOR_COOLING_LOOP_TEMP_AFTER_MOTOR_BYTE 0
#define MOTOR_COOLING_LOOP_TEMP_AFTER_MOTOR_LENGTH 2
#define MOTOR_COOLING_LOOP_TEMP_AFTER_MOTOR_TYPE int16_t
#define MOTOR_COOLING_LOOP_TEMP_AFTER_MOTOR_PREC 0.01f

#define MOTOR_COOLING_LOOP_TEMP_AFTER_INVERTER_BYTE 2
#define MOTOR_COOLING_LOOP_TEMP_AFTER_INVERTER_LENGTH 2
#define MOTOR_COOLING_LOOP_TEMP_AFTER_INVERTER_TYPE int16_t
#define MOTOR_COOLING_LOOP_TEMP_AFTER_INVERTER_PREC 0.01f

#define MOTOR_COOLING_TEMP_AFTER_RADIATOR_BYTE 4
#define MOTOR_COOLING_TEMP_AFTER_RADIATOR_LENGTH 2
#define MOTOR_COOLING_TEMP_AFTER_RADIATOR_TYPE int16_t
#define MOTOR_COOLING_TEMP_AFTER_RADIATOR_PREC 0.01f

#define MOTOR_COOLING_RADIATOR_FAN_SPEED_BYTE 6
#define MOTOR_COOLING_RADIATOR_FAN_SPEED_LENGTH 2
#define MOTOR_COOLING_RADIATOR_FAN_SPEED_TYPE uint16_t
#define MOTOR_COOLING_RADIATOR_FAN_SPEED_PREC 0.2f

// End Packet: Motor Cooling

// Packet: Battery Cooling
// From: VCU
// To:   Pi
#define BATTERY_COOLING_ID 259
#define BATTERY_COOLING_DLC 6
#define BATTERY_COOLING_FREQ 10
#define BATTERY_COOLING_QUANTITY 1

#define BATTERY_COOLING_TEMP_AFTER_BATTERY_BYTE 0
#define BATTERY_COOLING_TEMP_AFTER_BATTERY_LENGTH 2
#define BATTERY_COOLING_TEMP_AFTER_BATTERY_TYPE int16_t
#define BATTERY_COOLING_TEMP_AFTER_BATTERY_PREC 0.01f

#define BATTERY_COOLING_TEMP_AFTER_RADIATOR_BYTE 2
#define BATTERY_COOLING_TEMP_AFTER_RADIATOR_LENGTH 2
#define BATTERY_COOLING_TEMP_AFTER_RADIATOR_TYPE int16_t
#define BATTERY_COOLING_TEMP_AFTER_RADIATOR_PREC 0.01f

#define BATTERY_COOLING_RADIATOR_FAN_SPEED_BYTE 4
#define BATTERY_COOLING_RADIATOR_FAN_SPEED_LENGTH 2
#define BATTERY_COOLING_RADIATOR_FAN_SPEED_TYPE uint16_t
#define BATTERY_COOLING_RADIATOR_FAN_SPEED_PREC 0.2f

// End Packet: Battery Cooling

// Packet: Temps
// From: VCU
// To:   Pi
#define TEMPS_ID 260
#define TEMPS_DLC 6
#define TEMPS_FREQ 10
#define TEMPS_QUANTITY 1

#define TEMPS_INVERTER_BYTE 0
#define TEMPS_INVERTER_LENGTH 2
#define TEMPS_INVERTER_TYPE int16_t
#define TEMPS_INVERTER_PREC 0.01f

#define TEMPS_MOTOR_BYTE 2
#define TEMPS_MOTOR_LENGTH 2
#define TEMPS_MOTOR_TYPE int16_t
#define TEMPS_MOTOR_PREC 0.01f

#define TEMPS_AMBIENT_BYTE 4
#define TEMPS_AMBIENT_LENGTH 2
#define TEMPS_AMBIENT_TYPE int16_t
#define TEMPS_AMBIENT_PREC 0.01f

// End Packet: Temps

// Packet: Battery Pack Status
// From: HVC
// To:   Pi
#define BATTERY_PACK_STATUS_ID 512
#define BATTERY_PACK_STATUS_DLC 8
#define BATTERY_PACK_STATUS_FREQ 10
#define BATTERY_PACK_STATUS_QUANTITY 1

#define BATTERY_PACK_STATUS_PACK_VOLTAGE_BYTE 0
#define BATTERY_PACK_STATUS_PACK_VOLTAGE_LENGTH 2
#define BATTERY_PACK_STATUS_PACK_VOLTAGE_TYPE uint16_t
#define BATTERY_PACK_STATUS_PACK_VOLTAGE_PREC 0.01f

#define BATTERY_PACK_STATUS_TRACTIVE_CURRENT_BYTE 2
#define BATTERY_PACK_STATUS_TRACTIVE_CURRENT_LENGTH 2
#define BATTERY_PACK_STATUS_TRACTIVE_CURRENT_TYPE uint16_t
#define BATTERY_PACK_STATUS_TRACTIVE_CURRENT_PREC 0.01f

#define BATTERY_PACK_STATUS_STATE_OF_CHARGE_BYTE 4
#define BATTERY_PACK_STATUS_STATE_OF_CHARGE_LENGTH 2
#define BATTERY_PACK_STATUS_STATE_OF_CHARGE_TYPE uint16_t
#define BATTERY_PACK_STATUS_STATE_OF_CHARGE_PREC 0.01f

#define BATTERY_PACK_STATUS_CELL_TOP_TEMP_BYTE 6
#define BATTERY_PACK_STATUS_CELL_TOP_TEMP_LENGTH 1
#define BATTERY_PACK_STATUS_CELL_TOP_TEMP_TYPE uint8_t
#define BATTERY_PACK_STATUS_CELL_TOP_TEMP_PREC 1.0f

#define BATTERY_PACK_STATUS_CELL_BOTTOM_TEMP_BYTE 7
#define BATTERY_PACK_STATUS_CELL_BOTTOM_TEMP_LENGTH 1
#define BATTERY_PACK_STATUS_CELL_BOTTOM_TEMP_TYPE uint8_t
#define BATTERY_PACK_STATUS_CELL_BOTTOM_TEMP_PREC 1.0f

// End Packet: Battery Pack Status

// Packet: Battery Temperature Status
// From: HVC
// To:   Pi
#define BATTERY_TEMPERATURE_STATUS_ID 513
#define BATTERY_TEMPERATURE_STATUS_DLC 8
#define BATTERY_TEMPERATURE_STATUS_FREQ 100
#define BATTERY_TEMPERATURE_STATUS_QUANTITY 1

#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_1_TEMP_BYTE 0
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_1_TEMP_LENGTH 2
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_1_TEMP_TYPE uint16_t
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_1_TEMP_PREC 0.1f

#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_2_TEMP_BYTE 2
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_2_TEMP_LENGTH 2
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_2_TEMP_TYPE uint16_t
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_2_TEMP_PREC 0.1f

#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_3_TEMP_BYTE 4
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_3_TEMP_LENGTH 2
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_3_TEMP_TYPE uint16_t
#define BATTERY_TEMPERATURE_STATUS_BUS_BAR_3_TEMP_PREC 0.1f

#define BATTERY_TEMPERATURE_STATUS_PRECHARGE_RESISTOR_TEMP_BYTE 6
#define BATTERY_TEMPERATURE_STATUS_PRECHARGE_RESISTOR_TEMP_LENGTH 2
#define BATTERY_TEMPERATURE_STATUS_PRECHARGE_RESISTOR_TEMP_TYPE uint16_t
#define BATTERY_TEMPERATURE_STATUS_PRECHARGE_RESISTOR_TEMP_PREC 0.1f

// End Packet: Battery Temperature Status

// Packet: Indicators + Shutdown Status
// From: HVC
// To:   Pi
#define INDICATORS_SHUTDOWN_STATUS_ID 514
#define INDICATORS_SHUTDOWN_STATUS_DLC 6
#define INDICATORS_SHUTDOWN_STATUS_FREQ 100
#define INDICATORS_SHUTDOWN_STATUS_QUANTITY 1

#define INDICATORS_SHUTDOWN_STATUS_BMS_ERROR_BYTE 0
#define INDICATORS_SHUTDOWN_STATUS_BMS_ERROR_LENGTH 1
#define INDICATORS_SHUTDOWN_STATUS_BMS_ERROR_TYPE uint8_t
#define INDICATORS_SHUTDOWN_STATUS_BMS_ERROR_PREC 1.0f

#define INDICATORS_SHUTDOWN_STATUS_IMD_ERROR_BYTE 1
#define INDICATORS_SHUTDOWN_STATUS_IMD_ERROR_LENGTH 1
#define INDICATORS_SHUTDOWN_STATUS_IMD_ERROR_TYPE uint8_t
#define INDICATORS_SHUTDOWN_STATUS_IMD_ERROR_PREC 1.0f

#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_1_BYTE 2
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_1_LENGTH 1
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_1_TYPE uint8_t
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_1_PREC 1.0f

#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_2_BYTE 3
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_2_LENGTH 1
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_2_TYPE uint8_t
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_2_PREC 1.0f

#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_3_BYTE 4
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_3_LENGTH 1
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_3_TYPE uint8_t
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_3_PREC 1.0f

#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_4_BYTE 5
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_4_LENGTH 1
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_4_TYPE uint8_t
#define INDICATORS_SHUTDOWN_STATUS_SHUTDOWN_LEG_4_PREC 1.0f

// End Packet: Indicators + Shutdown Status

// Packet: Contactor Status
// From: HVC
// To:   Pi
#define CONTACTOR_STATUS_ID 515
#define CONTACTOR_STATUS_DLC 3
#define CONTACTOR_STATUS_FREQ 100
#define CONTACTOR_STATUS_QUANTITY 1

#define CONTACTOR_STATUS_HVC_STATE_MACHINE_BYTE 0
#define CONTACTOR_STATUS_HVC_STATE_MACHINE_LENGTH 1
#define CONTACTOR_STATUS_HVC_STATE_MACHINE_TYPE uint8_t
#define CONTACTOR_STATUS_HVC_STATE_MACHINE_PREC 1.0f

#define CONTACTOR_STATUS_POSITIVE_HV_CONTACTOR_BYTE 1
#define CONTACTOR_STATUS_POSITIVE_HV_CONTACTOR_LENGTH 1
#define CONTACTOR_STATUS_POSITIVE_HV_CONTACTOR_TYPE uint8_t
#define CONTACTOR_STATUS_POSITIVE_HV_CONTACTOR_PREC 1.0f

#define CONTACTOR_STATUS_NEGATIVE_HV_CONTACTOR_BYTE 2
#define CONTACTOR_STATUS_NEGATIVE_HV_CONTACTOR_LENGTH 1
#define CONTACTOR_STATUS_NEGATIVE_HV_CONTACTOR_TYPE uint8_t
#define CONTACTOR_STATUS_NEGATIVE_HV_CONTACTOR_PREC 1.0f

// End Packet: Contactor Status

// Packet: Cell Voltages
// From: HVC
// To:   Pi
#define CELL_VOLTAGES_ID 528
#define CELL_VOLTAGES_DLC 8
#define CELL_VOLTAGES_FREQ 1000
#define CELL_VOLTAGES_QUANTITY 35

#define CELL_VOLTAGES_VOLTAGE_I_BYTE 0
#define CELL_VOLTAGES_VOLTAGE_I_LENGTH 2
#define CELL_VOLTAGES_VOLTAGE_I_TYPE uint16_t
#define CELL_VOLTAGES_VOLTAGE_I_PREC 0.0001f

#define CELL_VOLTAGES_VOLTAGE_I_1_BYTE 2
#define CELL_VOLTAGES_VOLTAGE_I_1_LENGTH 2
#define CELL_VOLTAGES_VOLTAGE_I_1_TYPE uint16_t
#define CELL_VOLTAGES_VOLTAGE_I_1_PREC 0.0001f

#define CELL_VOLTAGES_VOLTAGE_I_2_BYTE 4
#define CELL_VOLTAGES_VOLTAGE_I_2_LENGTH 2
#define CELL_VOLTAGES_VOLTAGE_I_2_TYPE uint16_t
#define CELL_VOLTAGES_VOLTAGE_I_2_PREC 0.0001f

#define CELL_VOLTAGES_VOLTAGE_I_3_BYTE 6
#define CELL_VOLTAGES_VOLTAGE_I_3_LENGTH 2
#define CELL_VOLTAGES_VOLTAGE_I_3_TYPE uint16_t
#define CELL_VOLTAGES_VOLTAGE_I_3_PREC 0.0001f

// End Packet: Cell Voltages

// Packet: Cell Temperatures
// From: HVC
// To:   Pi
#define CELL_TEMPERATURES_ID 576
#define CELL_TEMPERATURES_DLC 8
#define CELL_TEMPERATURES_FREQ 1000
#define CELL_TEMPERATURES_QUANTITY 23

#define CELL_TEMPERATURES_TEMP_I_BYTE 0
#define CELL_TEMPERATURES_TEMP_I_LENGTH 2
#define CELL_TEMPERATURES_TEMP_I_TYPE uint16_t
#define CELL_TEMPERATURES_TEMP_I_PREC 0.1f

#define CELL_TEMPERATURES_TEMP_I_1_BYTE 2
#define CELL_TEMPERATURES_TEMP_I_1_LENGTH 2
#define CELL_TEMPERATURES_TEMP_I_1_TYPE uint16_t
#define CELL_TEMPERATURES_TEMP_I_1_PREC 0.1f

#define CELL_TEMPERATURES_TEMP_I_2_BYTE 4
#define CELL_TEMPERATURES_TEMP_I_2_LENGTH 2
#define CELL_TEMPERATURES_TEMP_I_2_TYPE uint16_t
#define CELL_TEMPERATURES_TEMP_I_2_PREC 0.1f

#define CELL_TEMPERATURES_TEMP_I_3_BYTE 6
#define CELL_TEMPERATURES_TEMP_I_3_LENGTH 2
#define CELL_TEMPERATURES_TEMP_I_3_TYPE uint16_t
#define CELL_TEMPERATURES_TEMP_I_3_PREC 0.1f

// End Packet: Cell Temperatures

// Packet: Allow Balance Command
// From: VCU
// To:   HVC
#define ALLOW_BALANCE_COMMAND_ID 261
#define ALLOW_BALANCE_COMMAND_DLC 0
#define ALLOW_BALANCE_COMMAND_FREQ 0
#define ALLOW_BALANCE_COMMAND_QUANTITY 0

// End Packet: Allow Balance Command

// Packet: HVC Bounds Parameters
// From: Pi
// To:   HVC
#define HVC_BOUNDS_PARAMETERS_ID 1536
#define HVC_BOUNDS_PARAMETERS_DLC 0
#define HVC_BOUNDS_PARAMETERS_FREQ 0
#define HVC_BOUNDS_PARAMETERS_QUANTITY 0

// End Packet: HVC Bounds Parameters

#endif // NIGHT_CAN_IDS_H
